
services:
  cities_frontend:
    image: cities/webapp
    build: https://github.com/PersonalKez/citiesApp_fe.git
    ports:
      - 8089:80

  cities_backend:
    image: cities/backend
    working_dir: /home/node/app
    build: https://github.com/PersonalKez/citiesApp_BE.git
    volumes:
      - node:/home/node/app
    ports:
      - 3000:3000

  mysql:
    image: mysql:8.0
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
      - cities-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cities 
  
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"

volumes:
  cities-mysql:
  node: