
services:
  cities_frontend:
    image: cities/webapp
    build: https://github.com/PersonalKez/citiesApp_fe.git

  cities_backend:
    image: cities/backend
    build: https://github.com/PersonalKez/citiesApp_BE.git

  mysql:
    image: mysql:8.0
    volumes:
      - cities-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cities 

volumes:
  cities-mysql: